#!/usr/bin/env python3
"""
Unified Beamer PDF Transition Page Remover
===========================================
Removes redundant intermediate/transition pages generated by LaTeX Beamer
animations (\\pause, \\onslide, \\item<n->, overlay specifications, etc.).

Detection Strategy (multi-signal, conservative):
──────────────────────────────────────────────
For each adjacent pair (page i, page i+1), after stripping ephemeral
footers (page numbers, slide counters):

  Level 1 — EXACT_MATCH:
    text_i == text_{i+1}  →  page i is a duplicate, REMOVE.
    (Same slide rendered on multiple physical pages; only page number differs.)

  Level 2 — STRICT_SUBSET:
    text_i ⊂ text_{i+1}  →  page i is an incomplete animation step, REMOVE.
    (Classic \\pause: content accumulates across pages.)

  Level 3 — WORD_SUBSET:
    words(text_i) ⊂ words(text_{i+1})  →  REMOVE with verification.
    (Catches reordered headers, e.g. "Outline" → "Overview Outline".)

  Level 4 — NEAR_DUPLICATE:
    text similarity ≥ 98% AND no unique content  →  REMOVE with warning.
    (Last-resort catch for text-extraction artifacts.)

  Otherwise  →  KEEP (page i is the final state of a slide).

Safety Overrides (any triggers → KEEP regardless):
  - Page i has unique images not present in page i+1.
  - Page i has unique text blocks not found anywhere in page i+1.
  - Page i has ≤ 10 non-whitespace characters (empty / image-only).

Always keeps the last page.

Usage:
    python3 dedup_beamer.py input.pdf [output.pdf] [--dry-run] [--verbose]
"""

import fitz  # PyMuPDF
import re
import sys
import os
import argparse
from dataclasses import dataclass, field
from typing import List, Set, Tuple, Optional

# ---------------------------------------------------------------------------
# Text cleaning
# ---------------------------------------------------------------------------

# Beamer footers: page numbers like "15 / 376", "15/376", "15 of 376"
PAGE_NUM_RE = re.compile(r"\d+\s*/\s*\d+")
# Standalone slide/frame counters at end of text: "15 / 376" or trailing " 15"
SLIDE_NUM_RE = re.compile(r"\s*\d+\s*/\s*\d+\s*")
# Bare trailing number (conservative: only strip if it's the very last thing)
TRAILING_NUM_RE = re.compile(r"\s+\d+\s*$")

# Characters that are often rendering artifacts in LaTeX PDFs
ARTIFACT_CHARS = ""  # control chars sometimes appearing in formulas


def clean_text(text: str) -> str:
    """
    Normalize text for comparison:
    1. Remove PDF artifact characters
    2. Remove page-number patterns (footers)
    3. Collapse whitespace
    4. Lowercase
    """
    for ch in ARTIFACT_CHARS:
        text = text.replace(ch, " ")
    text = PAGE_NUM_RE.sub(" ", text)
    text = SLIDE_NUM_RE.sub(" ", text)
    # Only strip a bare trailing number if the text is long enough
    # (avoid stripping content from very short pages)
    text = " ".join(text.split())
    return text.strip().lower()


def extract_page_text(page: fitz.Page) -> str:
    """Extract and clean all visible text from a PDF page."""
    raw = page.get_text("text")
    return clean_text(raw)


def extract_page_blocks(page: fitz.Page) -> List[str]:
    """
    Extract individual text blocks with their bounding boxes.
    Returns list of (x0, y0, x1, y1, cleaned_text).
    """
    blocks = page.get_text("blocks")
    result = []
    for b in blocks:
        if b[6] == 0:  # type 0 = text block
            block_text = clean_text(b[4])
            if block_text:  # skip empty blocks
                result.append((b[0], b[1], b[2], b[3], block_text))
    return result


def extract_page_images(page: fitz.Page) -> List[dict]:
    """Extract image metadata from a page."""
    return page.get_images(full=True)


# ---------------------------------------------------------------------------
# Comparison functions
# ---------------------------------------------------------------------------

def word_set(text: str) -> Set[str]:
    """Return the set of words in the text."""
    return set(text.split())


def jaccard_similarity(a: str, b: str) -> float:
    """Jaccard similarity on word sets. 1.0 = identical word sets."""
    wa = word_set(a)
    wb = word_set(b)
    if not wa and not wb:
        return 1.0
    if not wa or not wb:
        return 0.0
    return len(wa & wb) / len(wa | wb)


def has_unique_blocks(blocks_i: List[str], blocks_j: List[str]) -> bool:
    """
    Check if page i has any text block whose content is substantively
    absent from page j. Uses fuzzy word-overlap matching to avoid
    false positives when text is merely inserted into a block
    (e.g., "example" → "memoryless example").

    Returns True if page i has at least one block with <50% word
    overlap against the full text of page j.
    """
    all_text_j = " ".join(b[4] for b in blocks_j)
    words_j = set(all_text_j.split())

    for b in blocks_i:
        block_words = set(b[4].split())
        if not block_words:
            continue
        # What fraction of this block's words appear in page j?
        overlap = len(block_words & words_j) / len(block_words)
        if overlap < 0.5:
            return True
    return False


def has_unique_images(imgs_i: List[dict], imgs_j: List[dict]) -> bool:
    """
    Check if page i has images that page j does not.
    Compares by image content hash (or xref if available).
    Returns True if page i has unique images.
    """
    if not imgs_i:
        return False
    if not imgs_j:
        return True  # page i has images, page j has none

    # Compare by xref (unique object identifier in PDF)
    xrefs_j = {img[0] for img in imgs_j}
    xrefs_i = {img[0] for img in imgs_i}
    return bool(xrefs_i - xrefs_j)


# ---------------------------------------------------------------------------
# Decision data
# ---------------------------------------------------------------------------

@dataclass
class Decision:
    page_num: int           # 1-based page number
    action: str             # "KEEP" or "REMOVE"
    reason: str             # human-readable explanation
    confidence: str         # "HIGH", "MEDIUM", "LOW"
    detail: str = ""        # extra debug info


# ---------------------------------------------------------------------------
# Main dedup logic
# ---------------------------------------------------------------------------

def analyze_page_pair(
    page_num_i: int,
    text_i: str,
    text_j: str,
    blocks_i: List,
    blocks_j: List,
    imgs_i: List,
    imgs_j: List,
    verbose: bool = False,
) -> Decision:
    """
    Determine whether page i should be removed as a transition of page j.

    Returns a Decision object with the analysis result.
    """
    detail_parts = []

    # ---- Safety check: empty / near-empty page ----
    if len(text_i) <= 10:
        return Decision(
            page_num_i, "KEEP", "page has minimal text (≤10 chars)",
            "HIGH", "empty or near-empty page"
        )

    # ---- Level 1: EXACT_MATCH ----
    if text_i == text_j:
        detail = f"texts are identical ({len(text_i)} chars)"
        return Decision(page_num_i, "REMOVE", "exact duplicate", "HIGH", detail)

    # ---- Level 2: STRICT_SUBSET ----
    if text_i in text_j:
        extra = text_j.replace(text_i, "").strip()
        detail = f"text_i ({len(text_i)}c) ⊂ text_j ({len(text_j)}c), extra: '{extra[:80]}'"
        return Decision(page_num_i, "REMOVE", "strict text subset (pause transition)", "HIGH", detail)

    # ---- Level 3: WORD_SUBSET ----
    words_i = word_set(text_i)
    words_j = word_set(text_j)
    if words_i and words_i < words_j:  # strict subset
        extra_words = words_j - words_i
        detail = f"word sets: {len(words_i)} ⊂ {len(words_j)}, extra words: {extra_words}"
        return Decision(page_num_i, "REMOVE", "word-set subset", "HIGH", detail)

    # ---- Level 4: NEAR_DUPLICATE (high similarity) ----
    sim = jaccard_similarity(text_i, text_j)
    detail_parts.append(f"Jaccard sim={sim:.4f}")

    if sim >= 0.98:
        # High similarity — almost certainly the same slide
        # But do additional safety checks
        unique_blocks = has_unique_blocks(blocks_i, blocks_j)
        unique_imgs = has_unique_images(imgs_i, imgs_j)
        detail_parts.append(f"unique_blocks={unique_blocks}, unique_imgs={unique_imgs}")

        if unique_blocks:
            detail = "; ".join(detail_parts)
            return Decision(
                page_num_i, "KEEP",
                f"near-duplicate (sim={sim:.4f}) but has unique text blocks → keeping",
                "LOW", detail
            )

        if unique_imgs:
            detail = "; ".join(detail_parts)
            return Decision(
                page_num_i, "KEEP",
                f"near-duplicate (sim={sim:.4f}) but has unique images → keeping",
                "LOW", detail
            )

        # Both block and image checks pass → safe to remove
        detail = "; ".join(detail_parts)
        return Decision(
            page_num_i, "REMOVE",
            f"near-duplicate (similarity={sim:.4f})",
            "MEDIUM", detail
        )

    # ---- Default: KEEP ----
    detail = "; ".join(detail_parts) if detail_parts else ""
    return Decision(page_num_i, "KEEP", "has unique content not in next page", "HIGH", detail)


def dedup_pdf(
    input_path: str,
    output_path: Optional[str] = None,
    dry_run: bool = False,
    verbose: bool = False,
) -> Tuple[int, int]:
    """
    Main entry point. Returns (kept_count, removed_count).
    """
    if output_path is None:
        base, ext = os.path.splitext(input_path)
        output_path = f"{base}_clean{ext}"

    doc = fitz.open(input_path)
    total_pages = doc.page_count

    print(f"{'='*70}")
    print(f"Beamer PDF Deduplicator")
    print(f"{'='*70}")
    print(f"Input:  {input_path}")
    print(f"Output: {output_path}")
    print(f"Pages:  {total_pages}")
    if dry_run:
        print(f"Mode:   DRY RUN (no file will be written)")
    print(f"{'='*70}\n")

    # ---- Phase 1: Extract all page data ----
    print("Phase 1: Extracting text, blocks, and image metadata...")
    page_data = []
    for i in range(total_pages):
        page = doc[i]
        text = extract_page_text(page)
        blocks = extract_page_blocks(page)
        images = extract_page_images(page)
        page_data.append({
            "index": i,
            "text": text,
            "blocks": blocks,
            "images": images,
        })
        if verbose and i < 5:
            print(f"  Page {i+1:3d}: {len(blocks)} blocks, {len(images)} images, "
                  f"{len(text)} chars of text")
    print(f"  Done. Extracted data from {total_pages} pages.\n")

    # ---- Phase 2: Compare adjacent pairs ----
    print("Phase 2: Analyzing adjacent page pairs...\n")

    decisions: List[Decision] = []
    stats = {"EXACT_MATCH": 0, "STRICT_SUBSET": 0, "WORD_SUBSET": 0,
             "NEAR_DUPLICATE": 0, "KEPT": 0}

    for i in range(total_pages - 1):
        d = analyze_page_pair(
            page_num_i=i + 1,
            text_i=page_data[i]["text"],
            text_j=page_data[i + 1]["text"],
            blocks_i=page_data[i]["blocks"],
            blocks_j=page_data[i + 1]["blocks"],
            imgs_i=page_data[i]["images"],
            imgs_j=page_data[i + 1]["images"],
            verbose=verbose,
        )
        decisions.append(d)

        # Display
        if d.action == "REMOVE":
            symbol = "✗"
            if "exact duplicate" in d.reason:
                stats["EXACT_MATCH"] += 1
            elif "strict text subset" in d.reason:
                stats["STRICT_SUBSET"] += 1
            elif "word-set subset" in d.reason:
                stats["WORD_SUBSET"] += 1
            else:
                stats["NEAR_DUPLICATE"] += 1
        else:
            symbol = "✓"
            stats["KEPT"] += 1

        conf_marker = {"HIGH": " ", "MEDIUM": "~", "LOW": "!"}.get(d.confidence, "?")
        print(f"  {symbol}{conf_marker} Page {d.page_num:3d}  →  {d.action:6s}  "
              f"[{d.confidence:6s}] {d.reason}")

        if verbose and d.detail:
            print(f"           Detail: {d.detail}")

    # Last page always kept
    last_decision = Decision(
        total_pages, "KEEP", "last page (always kept)", "HIGH", ""
    )
    decisions.append(last_decision)
    stats["KEPT"] += 1
    print(f"  ✓ Page {total_pages:3d}  →  KEEP    [HIGH  ] last page (always kept)")

    # ---- Phase 3: Build output ----
    pages_to_keep = [d.page_num - 1 for d in decisions if d.action == "KEEP"]
    pages_to_remove = [d.page_num - 1 for d in decisions if d.action == "REMOVE"]

    kept = len(pages_to_keep)
    removed = len(pages_to_remove)

    print(f"\n{'='*70}")
    print(f"Summary")
    print(f"{'='*70}")
    print(f"  Pages kept:    {kept:4d}")
    print(f"  Pages removed: {removed:4d}")
    print(f"  Reduction:     {removed/total_pages*100:.1f}%")
    print(f"\n  Removal reasons:")
    print(f"    Exact duplicates:        {stats['EXACT_MATCH']:4d}")
    print(f"    Strict text subsets:     {stats['STRICT_SUBSET']:4d}")
    print(f"    Word-set subsets:        {stats['WORD_SUBSET']:4d}")
    print(f"    Near-duplicates:         {stats['NEAR_DUPLICATE']:4d}")

    # Show MEDIUM/LOW confidence removals for user review
    low_conf = [d for d in decisions if d.action == "REMOVE" and d.confidence != "HIGH"]
    if low_conf:
        print(f"\n  ⚠  Non-HIGH-confidence removals ({len(low_conf)}):")
        for d in low_conf:
            print(f"    Page {d.page_num:3d} [{d.confidence:6s}]: {d.reason}")

    if dry_run:
        print(f"\n  [DRY RUN] No file written.")
    else:
        # Delete pages in reverse order to preserve indices
        for idx in sorted(pages_to_remove, reverse=True):
            doc.delete_page(idx)

        doc.save(
            output_path,
            garbage=4,
            deflate=True,
            clean=True,
        )
        print(f"\n  Output written to: {output_path}")

        # Show file size comparison
        in_size = os.path.getsize(input_path)
        out_size = os.path.getsize(output_path)
        print(f"  Input size:  {in_size/1024/1024:.1f} MB")
        print(f"  Output size: {out_size/1024/1024:.1f} MB")

    doc.close()
    print(f"{'='*70}\n")
    return kept, removed


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------

def main():
    parser = argparse.ArgumentParser(
        description="Remove LaTeX Beamer transition/duplicate pages from a PDF.",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
  python3 dedup_beamer.py lecture.pdf
  python3 dedup_beamer.py lecture.pdf --dry-run
  python3 dedup_beamer.py lecture.pdf output.pdf --verbose
        """,
    )
    parser.add_argument("input", help="Input PDF file path")
    parser.add_argument("output", nargs="?", default=None,
                        help="Output PDF file path (default: <input>_clean.pdf)")
    parser.add_argument("--dry-run", action="store_true",
                        help="Analyze and report without writing output")
    parser.add_argument("--verbose", "-v", action="store_true",
                        help="Show detailed per-page diagnostics")
    args = parser.parse_args()

    if not os.path.exists(args.input):
        print(f"Error: input file not found: {args.input}")
        sys.exit(1)

    dedup_pdf(
        input_path=args.input,
        output_path=args.output,
        dry_run=args.dry_run,
        verbose=args.verbose,
    )


if __name__ == "__main__":
    main()
